### ISSUE TITLE
Image attributes?

### ISSUE THREAD

**Issue by mzmmohideen** [jrowellfx/lsseq#1]
Hi,
 This library was simply awesome. but i want to get attributes of each image along with it. so what to do? will i get with the help of this library or i need to do it manually? 

Thanks

**Comment by jrowellfx** [comment]
Hi Mohideen - thanks for the compliment!  I want to keep lsseq simple and have designed it following the general philosophy of unix tools in that they one one simple thing well. The way to get expanded features is to write other tools and chain them together with pipes etc.  lsseq is written to behave only like the traditional unix command 'ls' as far as it makes sense.

Anyway, sorry, I didn't, nor do I have plans to, expand lsseq like you as asking.

However, there are libraries to help with such tasks, like ImageMagick, or opencv.

You could write a new tool that given the native output of lsseq then lists the desired attribute[s] for the sequence in question, you could make a long listing that show attributes per file, or aggregate them and give averages, or highs and lows etc.. or show common attributes vs differing attributes etc..

Good luck!
James.
