### ISSUE TITLE
On Windows lsseq fails becuse of `ls`

### ISSUE THREAD

**Issue by badrigs999** [jrowellfx/lsseq#2]
running lsseq on windows without the -P flag fails as it trying to do the following
`
lsCmd = ["ls", "-d"] + extra_ls_options + otherFiles
`
is there a workaround for this ?

**Comment by jrowellfx** [comment]
I'll be happy to look into it for you- however I have never run lsseq on Windows before (only linux and mac) so would you mind please describing some more about the environment that you are running it in? What version of windows- what shell or command line are you using. How did you install it? As many details as possible that will help me to replicate the problem will be greatly appreciated. Thanks!
